language: php

sudo: false

env:
  global:
    - COMPOSER_ROOT_VERSION=1.0.x-dev

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: DB=MYSQL PHPUNIT_TEST=1
    - php: 7.2
      env: DB=MYSQL PHPUNIT_TEST=1 PHPCS_TEST=1
    - php: 7.3
      env: DB=MYSQL PHPUNIT_TEST=1

before_script:
  - composer self-update || true
  - export PATH=~/.composer/vendor/bin:$PATH
  - phpenv rehash
  - phpenv config-rm xdebug.ini
  - composer validate
  - composer install --prefer-dist
  - if [[ $PHPCS_TEST ]]; then composer global require squizlabs/php_codesniffer:^3 --prefer-dist --no-interaction --no-progress --no-suggest -o; fi

script:
  - if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit; fi
  - if [[ $PHPCS_TEST ]]; then composer run-script lint; fi
